import Head from 'next/head'
import Image from 'next/image'
import { Header } from '@/components/Home';
import { TopCards } from '@/components/TopCards';



export default function Home() {
  return (
    <>
      <Head>
        <title>Next Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <Header />
        <TopCards />
      </main>
    </>
  )
}
