import Head from 'next/head'
import Image from 'next/image'
import { Header } from '@/components/Home';
import { TopCards } from '@/components/TopCards';
import { BarChart } from '@/components/BarChart';
import { RecentOrders } from '@/components/RecentOrders';




export default function Home() {
  return (
    <>
      <Head>
        <title>Next Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=''>
        <Header />
        <TopCards />
        <div className='flex flex-col  w-auto'>
          <BarChart />
          <RecentOrders />
        </div>
      </main>
    </>
  )
}
